-- MySQL Script generated by MySQL Workbench
-- Tue Feb  9 22:08:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema electro8db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema electro8db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electro8db` DEFAULT CHARACTER SET utf8 ;
USE `electro8db` ;

-- -----------------------------------------------------
-- Table `electro8db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `profile` VARCHAR(100) NOT NULL,
  `image` VARCHAR(300) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electro8db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8db`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_price` DECIMAL(8,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_carts_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `electro8db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electro8db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8db`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electro8db`.`warranties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8db`.`warranties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `duration` INT UNSIGNED NULL DEFAULT NULL,
  `country_origin` VARCHAR(100) NULL DEFAULT NULL,
  `oficial_coverage` INT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electro8db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8db`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `brand` VARCHAR(100) NULL DEFAULT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `discount` DECIMAL(4,2) NOT NULL,
  `stock` INT UNSIGNED NOT NULL,
  `speed` INT UNSIGNED NULL DEFAULT NULL,
  `battery` INT UNSIGNED NULL DEFAULT NULL,
  `wheel` INT UNSIGNED NULL DEFAULT NULL,
  `light` INT UNSIGNED NULL DEFAULT NULL,
  `folding` INT UNSIGNED NULL DEFAULT NULL,
  `brake` VARCHAR(100) NULL DEFAULT NULL,
  `color` VARCHAR(100) NULL DEFAULT NULL,
  `weight` INT UNSIGNED NULL DEFAULT NULL,
  `image` VARCHAR(300) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `warranties_id` INT UNSIGNED NOT NULL,
  `categories_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_products_warranties1_idx` (`warranties_id` ASC) VISIBLE,
  INDEX `fk_products_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `electro8db`.`categories` (`id`),
  CONSTRAINT `fk_products_warranties1`
    FOREIGN KEY (`warranties_id`)
    REFERENCES `electro8db`.`warranties` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electro8db`.`cart_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8db`.`cart_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantity` INT UNSIGNED NOT NULL,
  `unit_price` DECIMAL(8,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `carts_id` INT NOT NULL,
  `products_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_cart_product_carts1_idx` (`carts_id` ASC) VISIBLE,
  INDEX `fk_cart_product_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_product_carts1`
    FOREIGN KEY (`carts_id`)
    REFERENCES `electro8db`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `electro8db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
