-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 19:59:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema electro8DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema electro8DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electro8DB` DEFAULT CHARACTER SET utf8 ;
USE `electro8DB` ;

-- -----------------------------------------------------
-- Table `electro8DB`.`warranties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8DB`.`warranties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `duration` INT UNSIGNED NULL,
  `country_origin` VARCHAR(100) NULL,
  `oficial_coverage` INT UNSIGNED NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electro8DB`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8DB`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `electro8DB`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8DB`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `description` VARCHAR(500) NULL,
  `discount` DECIMAL(4,2) NOT NULL,
  `stock` INT UNSIGNED NOT NULL,
  `speed` INT UNSIGNED NULL,
  `battery` INT UNSIGNED NULL,
  `wheel` INT UNSIGNED NULL,
  `light` INT UNSIGNED NULL,
  `folding` INT UNSIGNED NULL,
  `brake` VARCHAR(100) NULL,
  `color` VARCHAR(100) NULL,
  `weight` INT UNSIGNED NULL,
  `image` VARCHAR(300) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `warranties_id` INT UNSIGNED NOT NULL,
  `categories_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_products_warranties1_idx` (`warranties_id` ASC) VISIBLE,
  INDEX `fk_products_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_warranties1`
    FOREIGN KEY (`warranties_id`)
    REFERENCES `electro8DB`.`warranties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `electro8DB`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `electro8DB`.`user_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8DB`.`user_cart` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantity` INT UNSIGNED NOT NULL,
  `unit_price` DECIMAL(8,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `electro8DB`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8DB`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_price` DECIMAL(8,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `products_id` INT UNSIGNED NOT NULL,
  `user_cart_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_carts_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_carts_user_cart1_idx` (`user_cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `electro8DB`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_user_cart1`
    FOREIGN KEY (`user_cart_id`)
    REFERENCES `electro8DB`.`user_cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electro8DB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electro8DB`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(500) NULL,
  `profile` VARCHAR(100) NOT NULL,
  `image` VARCHAR(300) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `carts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_users_carts_idx` (`carts_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_carts`
    FOREIGN KEY (`carts_id`)
    REFERENCES `electro8DB`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
